### ISSUE TITLE
ArithmeticException: / by zero

### ISSUE THREAD

**Issue by mibby** [CaptainObvious0/NoCheatPlus#18]
Compiled as of commit https://github.com/CaptainObvious0/NoCheatPlus/commit/0519a7758bfe201700f2e15fcb647d59e162d28c (with fixed compilation error).

RE: https://github.com/CaptainObvious0/NoCheatPlus/issues/16

@CaptainObvious0 Issue refuses to go away. :P Seems to be on any type of virtual container as the player opened a reward claim window, their virtual chest storage, their daily bonus claim NPC, their virtual enderchest, the server GUI menu, etc. 

(I have far too many virtual container features that makes it nearly impossible to list all in NCP's config.)

https://paste.ubuntu.com/p/Tv3p4JZg56/

**Comment by CaptainObvious0** [comment]
Some changes need to be made to the check then.

Will be fixed later.

**Comment by andris155** [comment]
Same problem.

**Comment by En0tS** [comment]
Same: https://pastebin.com/H0z94pcK

**Comment by CaptainObvious0** [comment]
fastClickChest will now check for values being zero, to prevent any errors.

Fixed with ba2ab53 , closing issue.
