### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by mibby** [CaptainObvious0/NoCheatPlus#19]
RE: https://github.com/CaptainObvious0/NoCheatPlus/commit/0519a7758bfe201700f2e15fcb647d59e162d28c#commitcomment-33028687

Caused here.
https://github.com/CaptainObvious0/NoCheatPlus/blob/0519a7758bfe201700f2e15fcb647d59e162d28c/NCPCore/src/main/java/fr/neatmonster/nocheatplus/config/DefaultConfig.java#L781

Removing line 781-790, compilation works fine.

**Comment by CaptainObvious0** [comment]
Attempted fix with 5891be2

Can not confirm this works. Will test later.

**Comment by andris155** [comment]
The fix works perfectly. Thanks.

**Comment by MarkElf** [comment]
I hope that my contribution didn't case more trouble than it was worth. I probably should have disclaimed that there may be mistakes and to double check for mistakes but it definitely wasn't intentional.

**Comment by CaptainObvious0** [comment]
@MarkElf No worries.

Closing as @andris155 confirms it has been fixed.
