### ISSUE TITLE
Strange Text

### ISSUE THREAD

**Issue by Kyrobi** [CaptainObvious0/NoCheatPlus#22]
### Full output of /ncp version

---- Version information ----
#### Server ####
git-Paper-588 ~MC: 1.13.2~
  detected: 1.13.2
#### NoCheatPlus ####
Plugin: 3.16.1-SNAPSHOT-CustomFork-v1.2
MCAccess: 1.4.5-1.12.2|? / CB-Reflect
Features:
  blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10 | BlocksMC1_11 | BlocksMC1_12 | BlocksMC1_13
  checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter | AttackFrequency | FlyingFrequency | KeepAliveFrequency
  defaults: pvpKnockBackVelocity
  packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance
Hooks: AllViolations~NCP~ 1.0 | mcMMO~cncp~ 2.3
#### Related Plugins ####
CompatNoCheatPlus v6.6.6-SNAPSHOT-sMD5NET-b91 | ProtocolLib v4.4.0 | ProtocolSupport v4.29-dev

### Describe the issue 
Updated the 1.13beta3; strange messages appearing in chat. Something like "vDistRel: BedLeaveTime: 0 Bed "

### How to reproduce the issue
Unknown

### Extra links/Videos (Including debug logs) 
http://prntscr.com/n8wlrm

### Any possible config options changed or plugins that may cause interference?
No configuration settings were change.

Edit: That image is from a normal player  who doesn't have op / admin rank.

**Comment by CaptainObvious0** [comment]
Update to a newer version. I used that for debugging but I may have accidentally added it with some other versions. Currently, I don’t see that message anywhere on the GitHub page.
