### ISSUE TITLE
SurvivalFly and CreativeFly + debug mode.

### ISSUE THREAD

**Issue by Lysandr0** [CaptainObvious0/NoCheatPlus#25]
### Full output of /ncp version
```
[INFO] ---- Version information ----
[INFO] #### Server ####
[INFO] git-Spigot-e6eb36f-d3ed151 ~MC: 1.13.2~
[INFO] detected: 1.13.2
[INFO] #### NoCheatPlus ####
[INFO] Plugin: 3.16.1-SNAPSHOT-CustomFork-v1.3-beta.3
[INFO] MCAccess: 1.4.5-1.12.2|? / CB-Reflect
[INFO] Features:
[INFO] blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10 | BlocksMC1_11 | BlocksMC1_12 | BlocksMC1_13
[INFO] checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter | AttackFrequency | FlyingFrequency | KeepAliveFrequency
[INFO] defaults: pvpKnockBackVelocity
[INFO] packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance | DebugAdapter
[INFO] Hooks: AllViolations~NCP~ 1.0
[INFO] #### Related Plugins ####
[INFO] ProtocolLib v4.4.0 | ProtocolSupport v4.29-dev
```

### Describe the issue
These are a bunch of issues I reported to the original NCP’s issues tracker some time ago and thought I might bring ‘em here in a single ticket, since they probably share the same issue. :p

Both SurvivalFly and CreativeFly behave differently when you run the debug command;
CreativeFly will block elytra-fly cheats, as expected, but it won’t do anything to prevent those if the debug mode is disabled. [(#560)](https://github.com/NoCheatPlus/Issues/issues/560)
SurvivalFly will throw out a lot of false positives when you fly around, but it won’t if you run the debug command.  ([#539](https://github.com/NoCheatPlus/Issues/issues/539))

  Eventually, after some investigation I found out that this bug appeared after asofold deployed build [#1137](https://ci.md-5.net/job/NoCheatPlus/1137/) 

### Extra links/Videos (Including debug logs)
Any logs can be found over the original tickets
https://www.dropbox.com/s/2qbfh0syyrz0wjl/ElytraFly.mov?dl=0
https://www.dropbox.com/s/xsfwdr7hau81si7/SurvivalFly.mov?dl=0
(excuse the poor quality/fps... :p)

**Comment by CaptainObvious0** [comment]
Possibly the debug command changes some mechanics. I have a suspicion that data-reset (SurvivalFly issue) plays a role in this, possibly having debug enabled does not do a data reset. 

I’ll have to look further into the CreativeFly issue, as I haven’t experienced this issue before.

Thanks for reporting. I want to start to fix those long unfixed issues.

**Comment by CaptainObvious0** [comment]
Attempted fix with 75eaab9 

I'm able to confirm that these changes fix the false positives in survival mode flying, but I wasn't able to confirm the elytra issues are fixed. Keeping this open until you can confirm.

**Comment by Lysandr0** [comment]
I'd need the release of the .jar file first... Unfortunately I don't have the knowledge required to compile NoCheatPlus. :p

**Comment by Kyrobi** [comment]
> I'd need the release of the .jar file first... Unfortunately I don't have the knowledge required to compile NoCheatPlus. :p

If you still need a build in the next 6~ hours, I'll build it for you. At school right now so I can't do much :p

**Comment by Lysandr0** [comment]
If this won't take too much of your time or bother you in any way, I'd be really grateful :)

**Comment by Kyrobi** [comment]
> If this won't take too much of your time or bother you in any way, I'd be really grateful :)

Done! Here ya go: https://drive.google.com/file/d/1bh-w8Z9qI1r2NUw3Q-COoVeK-PmzbRMb/view?usp=sharing

**Comment by Lysandr0** [comment]
Thank you a lot! @Kyrobi 
I'll be testing the fix attempt right away~

_Edit:_ the commit [75eaab9](https://github.com/CaptainObvious0/NoCheatPlus/commit/75eaab9da0bfa0ffe6bae487c014cd41dbc6f40f) solves the CreativeFly issue as well, this can be closed/marked as fixed :p

**Comment by CaptainObvious0** [comment]
@Kyrobi thanks for helping them out, sorry I wasn't able to respond sooner. 

Any commits pushed after a release can be considered an alpha version, as I may not have fully tested everything yet. If you're running a server, I strongly recommend not build from the latest commit, build from the latest release. 

I'm finishing up some changes to swimming, after that I'll push a new release.
