### ISSUE TITLE
Phase FP

### ISSUE THREAD

**Issue by Kyrobi** [CaptainObvious0/NoCheatPlus#27]
### Full output of /ncp version
---- Version information ----
#### Server ####
git-Paper-588 ~MC: 1.13.2~
  detected: 1.13.2
#### NoCheatPlus ####
Plugin: 3.16.1-SNAPSHOT-b1153-CustomFork
MCAccess: 1.4.5-1.12.2|? / CB-Reflect
Features:
  blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10 | BlocksMC1_11 | BlocksMC1_12 | BlocksMC1_13
  checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter | AttackFrequency | FlyingFrequency | KeepAliveFrequency
  defaults: pvpKnockBackVelocity
  packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance
Hooks: AllViolations~NCP~ 1.0 | mcMMO~cncp~ 2.3
#### Related Plugins ####
CompatNoCheatPlus v6.6.6-SNAPSHOT-sMD5NET-b91 | ProtocolLib v4.4.0 | ProtocolSupport v4.29-dev

### Describe the issue
When going up a spiral staircase made of half-slab, despite the fact that there's just enough clearance, it'll flag you for phase. 

### How to reproduce the issue
Spiral staircase. Also see video

### Extra links/Videos (Including debug logs)
https://youtu.be/dO1x0dxkn4o

### Any possible config options changed or plugins that may cause interference?
No config change. 

Verbose notification: https://imgur.com/a/8M7HsiD

P.S. There's enough clearance to walk up

**Comment by CaptainObvious0** [comment]
For now, I would add `ign_passable` to each slab in the config. It seems some of the flags aren't correct when the block is placed on the top half rather than the lower half. 

Further investigation into this issue will be required. Possibly other flags need to be applied or something needs to be changed within the code.

**Comment by MarkElf** [comment]
I've found the low jump flag fixes movement on top half slabs.

**Comment by CaptainObvious0** [comment]
Fixed with default block modeling, but this will not be added in a release until all blocks are finished #40
