### ISSUE TITLE
Falling on to beds from large distances

### ISSUE THREAD

**Issue by CaptainObvious0** [CaptainObvious0/NoCheatPlus#30]
Flags for vdistrel.

Some sort of flag could be applied to allow a slight bounce, similar to slime blocks. Occurs at heights above 5 blocks.

**Comment by FabioZumbi12** [comment]
Maybe is related, when walking under repeaters andcomparator, getting the message in-game `vDistRel: BedLeaveTime: 0 Bed = now: 15549596702793` spamming on player chats.

If is not related let me know to open another issue.

**Comment by CaptainObvious0** [comment]
@FabioZumbi12 You will need to update. I accidentally left in some messages I used for testing in an older version.

**Comment by CaptainObvious0** [comment]
After debugging for more than I should have, the issue was caused by the wrong blockY being used causing a method to return false, never applying the jump flag to the move/block. Fixed in  5b6e090
