### ISSUE TITLE
/ncp commands not working

### ISSUE THREAD

**Issue by Kyrobi** [CaptainObvious0/NoCheatPlus#31]
#### Server ####
git-Paper-588 ~MC: 1.13.2~
  detected: 1.13.2
#### NoCheatPlus ####
Plugin: 3.16.1-SNAPSHOT-b1153-CustomFork
MCAccess: 1.13|? / Bukkit-API
Features:
  blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10 | BlocksMC1_11 | BlocksMC1_12 | BlocksMC1_13 | MCAccessBukkitModern
  checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter | FlyingFrequency | KeepAliveFrequency
  defaults: pvpKnockBackVelocity
  packet-listeners: MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance
Hooks: AllViolations~NCP~ 1.0 | mcMMO~cncp~ 2.3
#### Related Plugins ####
CompatNoCheatPlus v6.6.6-SNAPSHOT-sMD5NET-b91 | ProtocolLib v4.4.0

### Describe the issue
When in-game, using any /ncp command will just show you the help message. 

### How to reproduce the issue
Just join a server and try to use something like /ncp notify on

### Extra links/Videos (Including debug logs)
https://youtu.be/rCWEXAgKntA

### Any possible config options changed or plugins that may cause interference?
No change.

Note: Commands issued through console work. Player in-game has sufficient perms

**Comment by CaptainObvious0** [comment]
Nothing has been changed with commands or anything that would interfere with it. My suspicion would be that permissions aren’t added correctly. If you have access to one NoCheatPlus permission it will allow you to see the help message but will not allow you to use any other command and return with the help message. Does the issue continue if you are op?
