### ISSUE TITLE
regular player seeing notification

### ISSUE THREAD

**Issue by PhanaticD** [CaptainObvious0/NoCheatPlus#34]
a regular player with no special perms told me in chat it says vDistRel: BedLeaveTime: 0 Bed - now: 1554976168095

**Comment by Kyrobi** [comment]
Update to a newer version. CaptainObvious0 used that for debugging but her may have accidentally added it with some other versions. Just update the the newest version, I'm currently getting no such thing on the newest version.

**Comment by CaptainObvious0** [comment]
As @Kyrobi said, update to a newer version and the problem will be fixed.
