### ISSUE TITLE
Snow layer FP (Unimportant)

### ISSUE THREAD

**Issue by Kyrobi** [CaptainObvious0/NoCheatPlus#35]
#### Server ####
git-Paper-588 ~MC: 1.13.2~
  detected: 1.13.2
#### NoCheatPlus ####
Plugin: 3.16.1-SNAPSHOT-b1153-CustomFork
MCAccess: 1.13|? / Bukkit-API
Features:
  blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10 | BlocksMC1_11 | BlocksMC1_12 | BlocksMC1_13 | MCAccessBukkitModern
  checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter | FlyingFrequency | KeepAliveFrequency
  defaults: pvpKnockBackVelocity
  packet-listeners: MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance
Hooks: AllViolations~NCP~ 1.0 | mcMMO~cncp~ 2.3
#### Related Plugins ####
CompatNoCheatPlus v6.6.6-SNAPSHOT-sMD5NET-b91 | ProtocolLib v4.4.0

### Describe the issue
When sprinting and jumping up a "snow-layer staircase", it will occasionally set you back for survival fly.

### How to reproduce the issue
In video

### Extra links/Videos (Including debug logs)
https://youtu.be/4WdCtNsJBA0 (Debug included in video)

### Any possible config options changed or plugins that may cause interference?
No change.

**Comment by CaptainObvious0** [comment]
Thanks for reporting, I'll check this out later.

In the future, a debug log refers to this: https://github.com/NoCheatPlus/Docs/wiki/Debugging#on-the-fly-debug-output-for-individual-players

**Comment by CaptainObvious0** [comment]
Fixed with dec9f75
