### ISSUE TITLE
Falling bug

### ISSUE THREAD

**Issue by andris155** [CaptainObvious0/NoCheatPlus#36]
### Full output of /ncp version
```
12.04 14:37:47 [Server] INFO ---- Version information ----
12.04 14:37:47 [Server] INFO #### Server ####
12.04 14:37:47 [Server] INFO git-Paper-610 ~MC: 1.13.2~
12.04 14:37:47 [Server] INFO detected: 1.13.2
12.04 14:37:47 [Server] INFO #### NoCheatPlus ####
12.04 14:37:47 [Server] INFO Plugin: 3.16.1-SNAPSHOT-CustomFork-v1.2
12.04 14:37:47 [Server] INFO MCAccess: 1.4.5-1.12.2|? / CB-Reflect
12.04 14:37:47 [Server] INFO Features:
12.04 14:37:47 [Server] INFO blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10 | BlocksMC1_11 | BlocksMC1_12 | BlocksMC1_13
12.04 14:37:47 [Server] INFO checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter | AttackFrequency | FlyingFrequency | KeepAliveFrequency
12.04 14:37:47 [Server] INFO defaults: pvpKnockBackVelocity
12.04 14:37:47 [Server] INFO packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance
12.04 14:37:47 [Server] INFO Hooks: AllViolations~NCP~ 1.0 | Citizens2~cncp~ 2.0 | mcMMO~cncp~ 2.3 | MyPet 1.1
12.04 14:37:47 [Server] INFO #### Related Plugins ####
12.04 14:37:47 [Server] INFO CompatNoCheatPlus v6.6.6-SNAPSHOT-sMD5NET-b91 | ProtocolLib v4.4.0 | ViaVersion v2.0.0-SNAPSHOT
```

### Describe the issue
Falling bug

### How to reproduce the issue
Fly up and fall.

### Extra links/Videos (Including debug logs)
https://imgur.com/a/C97xhap
https://imgur.com/a/z4zVWOf

### Any possible config options changed or plugins that may cause interference?
I used this config: https://www.mc-market.org/resources/475/

**Comment by MarkElf** [comment]
Try the following jar to see if the issue continues to occur as there does seem to be recent changes to survivalfly that may already resolve this. Compiled by @Kyrobi and is about 3 days old now - https://drive.google.com/file/d/1bh-w8Z9qI1r2NUw3Q-COoVeK-PmzbRMb/view

Note for reference, mostly for myself, a simple picture by picture or short video on compiling the jar would be nice as I'd like to tinker with things before pushing a PR to avoid the mess I made last time. There is a word guide but I'm not sure it's something I can follow as I haven't used Marvin.

**Comment by CaptainObvious0** [comment]
Most false positives with legally flying while in survival have been fixed, just an update hasn't been released yet. I finished up finalizing the magic speeds but ran into another issue that will be addressed before the update is released. 

I’ll make a wiki page explaining how to build using maven.
