### ISSUE TITLE
FightSync Improvements - Ping/TPS Integration

### ISSUE THREAD

**Issue by andris155** [CaptainObvious0/NoCheatPlus#37]
Fightsync flood on chat, and active: false setting not work. Please fix this.

**Comment by CaptainObvious0** [comment]
Please use the proper reporting format. 

I’ll need more information as well. Latency can probably play a big role, so that can be added. For now, remove logging from the actions list.

**Comment by andris155** [comment]
The ping 40-50, because server location in France, but players from Hungary.

**Comment by CaptainObvious0** [comment]
Enabling/Disabling the check has been fixed with 0d65210 

Further improvements will come in the future. Some sort of latency/tps leniency should be integrated, possibly even attempting to match up estimated packet arrival time with the players ping.

**Comment by CaptainObvious0** [comment]
Will most likely remove FightSync check and work on other things found here: https://github.com/CaptainObvious0/NoCheatPlus/issues/51
