### ISSUE TITLE
ElytraFly Check

### ISSUE THREAD

**Issue by Kyrobi** [CaptainObvious0/NoCheatPlus#39]
### Describe the features of this added check
This will stop a hack module that allows you to fly with an elytra without the use of fireworks.
Another one this the module that basically gives you more control over elytra. This also makes you able to fly without the use of fireworks.

### Any extra information about what should be added? (Config options...)
Technically NCP flags the elytra hack as **creative fly**, but doesn't generate any debug for some reason even though it one. Survival fly generates debug just fine. 

Log: https://imgur.com/a/vXmGiUO
Video: https://www.youtube.com/watch?v=eke2HkSNrl4

**Comment by CaptainObvious0** [comment]
An elytra check has already been added a long time ago. Are you sure you're running the latest release? It blocks just fine when I tested it.

**Comment by Kyrobi** [comment]
Woops, NoCheatPlus wasn't enabled enabled lol
