### ISSUE TITLE
Block Modeling Progress

### ISSUE THREAD

**Issue by CaptainObvious0** [CaptainObvious0/NoCheatPlus#40]
### Need to be modeled:
- [x] Conduit 
- [x] Cocoa beans
- [x] Sea Pickle
- [x] Chorus Plant
- [x] Wall Heads
- [x] Turtle Egg

### Some special flags need to be added by default:

- [x] Beds - Sprint + Jumping allowing for slight bounce on long periods of beds will flag for hspeed. (Merge issue with #30 )
- [x] Shulker Boxes - Models are correct, but closing/opening multiple times while on top will flag
- [x] Anvil - The lower section of the anvil needs to be added. 

### No issues, but need to be defined
- [x] Beacon
- [x] Cake
- [x] Kelp Plant, All dead coral, sea grass (Keeping config modeling, need to figure out another issue)
- [x] Ladder, Vine

**Comment by CaptainObvious0** [comment]
Notes: 
* It seems that with some of the models I add, the onground checking is not working, which causes some issues. This will be investigated later. For now, I've added a workaround to make the blocks fully passable.

**Comment by kotarobo** [comment]
Is it due to block modeling that the movement is canceled when jumping to the half block pasted on the ceiling?

**Comment by CaptainObvious0** [comment]
All blocks should be modeled with latest commit.

**Comment by MarkElf** [comment]
(Dead) Coral is still undefined and is using the blockoverride section in the configuration. I assume it would be safe to define them as ign_passable with the waterblock flag that I can't remember off the top of my head.
