### ISSUE TITLE
FP: Dangerous Kelp

### ISSUE THREAD

**Issue by Kyrobi** [CaptainObvious0/NoCheatPlus#41]
#### Server ####
git-Paper-588 ~MC: 1.13.2~
  detected: 1.13.2
#### NoCheatPlus ####
Plugin: 3.16.1-SNAPSHOT-b1153-CustomFork
MCAccess: 1.13|? / Bukkit-API
Features:
  blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10 | BlocksMC1_11 | BlocksMC1_12 | BlocksMC1_13 | MCAccessBukkitModern
  checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter | FlyingFrequency | KeepAliveFrequency
  defaults: pvpKnockBackVelocity
  packet-listeners: MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance
Hooks: AllViolations~NCP~ 1.0 | mcMMO~cncp~ 2.3
#### Related Plugins ####
CompatNoCheatPlus v6.6.6-SNAPSHOT-sMD5NET-b91 | ProtocolLib v4.4.0

### Describe the issue
Kelp is a dangerous thing. Going into it will do let you swim up.

### How to reproduce the issue
Go to an area with kelp and to swim up. Also in the video

### Extra links/Videos (Including debug logs)
https://youtu.be/qcHrcncQZas

### Any possible config options changed or plugins that may cause interference?
Default config generated by the plugin first load. (Just that debug is turned on)

**Comment by Kyrobi** [comment]
Realized that the debug thing was hard to see in the video. Here's a pastebin thing: https://pastebin.com/vLFvPvR5

**Comment by CaptainObvious0** [comment]
Add `liquid+water` to kelp flags. 

Did you build of the latest commit or latest release? Thank you for providing the debug log, it is really useful.

**Comment by Kyrobi** [comment]
Info for any others who have problems with kelp: Don't add the `water` tag to it. Sure it makes you able to swim up through kept fine, but it makes the kelp unbreakable. If you break it, it'll just appear back. I recommend using this flag (from sea pickles) instead: `default+ground_height+ground`

**Comment by CaptainObvious0** [comment]
Good to know, I'll reference this when modeling the liquid blocks.
