### ISSUE TITLE
Riptide Trident FP

### ISSUE THREAD

**Issue by Kyrobi** [CaptainObvious0/NoCheatPlus#45]
### Full output of /ncp version
https://imgur.com/a/c4ZvUze

### Describe the issue
When a player tries to launch _straight up_ out of the water, they'll get teleported back.
Sometimes once the server teleports the player back, they're instantly killed.

### How to reproduce the issue
Launch straight up with a trident that has riptide 3.

### Extra links/Videos (Including debug logs)
https://imgur.com/a/DhARugq
https://pastebin.com/hUNiPYru
Video: https://youtu.be/naVqxa5i_Ys (I find the end pretty funny)

### Any possible config options changed or plugins that may cause interference?
Tested with both of the configs:
1. MarkElf's config
2.  And the one from here: https://github.com/CaptainObvious0/NoCheatPlus/tree/master/NCP%20Config/Notify%20Only

I tried tweaking the violations around, but it comes with a compromise.
When using a hacked client for elytra, it'll generate anywhere from 50VLs to 330VLs.

When using the trident to launch yourself straight up. it generates about 300-450~ VLs.

So I can set the VLs high which will fix the Trident issue, but I'll also allow ElytraBoost hack to work.

**Comment by CaptainObvious0** [comment]
Issue should be fixed with latest commit.
