### ISSUE TITLE
[SurvivalFly Bug Report] Toggling flight in sky gives a false positive

### ISSUE THREAD

**Issue by ygtdmn** [CaptainObvious0/NoCheatPlus#46]
### Full output of /ncp version
http://prntscr.com/nfqgib
### Describe the issue
It is replica of this issue: https://github.com/NoCheatPlus/Issues/issues/539
I just wanted to report this to you as well because apparently original NoCheatPlus won't be updated.
### How to reproduce the issue
Fly and double jump in sky to toggling off flying. 
### Any possible config options changed or plugins that may cause interference?
MarkElf's config.

**Comment by CaptainObvious0** [comment]
This version of NoCheatPlus is only for 1.13. This issue has already been fixed.
