### ISSUE TITLE
Slow Falling Potion FP

### ISSUE THREAD

**Issue by Kyrobi** [CaptainObvious0/NoCheatPlus#52]
### Full output of /ncp version
https://pastebin.com/J6S8QbgU

### Describe the issue
When a slow falling potion has been consumed, the player is not able to jump off a pillar / ledge / dig again the block underneath them without triggering the survival fly.

### How to reproduce the issue
Walk off a ledge with slow falling.

### Extra links/Videos (Including debug logs)
Video: https://youtu.be/vJ05e-jxdHA
Debug: https://pastebin.com/UAvdqpc0

### Any possible config options changed or plugins that may cause interference?
No config change.
Test server config is the same as the production server but with debug on.
Config link: https://pastebin.com/pr8mc3u1

**Comment by BetaBurnt** [comment]
Any possible patch/fix for this? Currently the only way I've gotten it to allow slow falling properly is to disable the survival fly checks entirely - setting it to have a very high violation level helped somewhat but then it gave weird effects when teleporting with slow fall on. Could the plugin not just be set to ignore a player if they have the slow fall potion effect on?

**Comment by CaptainObvious0** [comment]
Should be supported in the latest commit.
