### ISSUE TITLE
.

### ISSUE THREAD

**Issue by 0zelot** [CaptainObvious0/NoCheatPlus#53]
.

**Comment by Kyrobi** [comment]
> NCP detects fly and kicks players when they are standing on EndRod. (player.survivalfly)

Graduations! Thanks for completely ignoring the issue template and providing no other information, really appreciate your contribution!

Please open another issue and supply the required information. Regards to the end rod, I was **not** able to replicate such issue.

Video proof: https://youtu.be/PFziBqrx5WM

**Comment by CaptainObvious0** [comment]
Invalid until proper information is provided.
