### ISSUE TITLE
Create a jenkins server please

### ISSUE THREAD

**Issue by Kongolan** [CaptainObvious0/NoCheatPlus#54]
Can you build a jenkins server please for it? It's free as far as I know, but forking the project and compiling it on my pc is not the best solution for a project, which I don't maintain much.

**Comment by CaptainObvious0** [comment]
You can find the latest build @ https://ci.codemc.io/job/CaptainObvious0/job/NoCheatPlus-1.15-CaptainObvious0/ :)
