### ISSUE TITLE
Exception with AutoListener

### ISSUE THREAD

**Issue by LaughNgamez** [CaptainObvious0/NoCheatPlus#56]
### Full output of /ncp version
https://pastebin.com/vSJmLxHQ

### Describe the issue
This error occurs in console when I walk on my server https://pastebin.com/UPV2nycg

### How to reproduce the issue
Not sure, walk on my server

### Any possible config options changed or plugins that may cause interference?
I am running 1.12 and using ViaVersion so maybe that's related?

**Comment by CaptainObvious0** [comment]
1.12 is currently not supported with this fork. Use the latest dev build instead.
