### ISSUE TITLE
1.14: berry bush movement model

### ISSUE THREAD

**Issue by Lysandr0** [CaptainObvious0/NoCheatPlus#62]
### Full output of /ncp version
```
[INFO] ---- Version information ----
[INFO] #### Server ####
[INFO] git-Spigot-94af569-5d335e9 ~MC: 1.14.4~
[INFO] detected: 1.14.4
[INFO] #### NoCheatPlus ####
[INFO] Plugin: 3.16.1-SNAPSHOT-b1153-CustomFork
[INFO] MCAccess: 1.13-1.14.4|? / Bukkit-API
[INFO] Features:
[INFO] blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10 | BlocksMC1_11 | BlocksMC1_12 | BlocksMC1_13 | BlocksMC1_14 | MCAccessBukkitModern
[INFO] checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter | AttackFrequency | FlyingFrequency | KeepAliveFrequency
[INFO] defaults: pvpKnockBackVelocity
[INFO] packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance | NoSlow
[INFO] Hooks: AllViolations~NCP~ 1.0
[INFO] #### Related Plugins ####
[INFO] ProtocolLib v4.5.0-SNAPSHOT
```
### Describe the issue
Trying to jump through berry bushes will result in massive false positives most of the time, so a dedicated speed/move model would be great to have.

In the video at 01.12, you can also notice how NCP makes you perform a shorter jump compared to vanilla MC. 
### Extra links/Videos (Including debug logs)
https://www.dropbox.com/s/3rs6b93rx333vlg/berry_bush_fp.mov?dl=0

### Any possible config options changed or plugins that may cause interference?
Default config, with @xaw3ep commits applied

**Comment by CaptainObvious0** [comment]
“ I defined berry bush wrongly as thought it same like cobweb but seem like it can move a bit faster so the best way to fix is set it like a passable block.” - xaw3ep

**Comment by Lysandr0** [comment]
On an unrelated note: on which tracker should we report issues? :p

**Comment by Lysandr0** [comment]
Fixed on @xaw3ep's fork.
