### ISSUE TITLE
SurvivalFly: allow the elytra to accelerate the player when trying to take off from ground

### ISSUE THREAD

**Issue by Lysandr0** [CaptainObvious0/NoCheatPlus#64]
### Full output of /ncp version
```
[INFO] ---- Version information ----
[INFO] #### Server ####
[INFO] git-Spigot-94af569-5d335e9 ~MC: 1.14.4~
[INFO] detected: 1.14.4
[INFO] #### NoCheatPlus ####
[INFO] Plugin: 3.16.1-SNAPSHOT-b1153-CustomFork
[INFO] MCAccess: 1.13-1.14.4|? / Bukkit-API
[INFO] Features:
[INFO] blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10 | BlocksMC1_11 | BlocksMC1_12 | BlocksMC1_13 | BlocksMC1_14 | MCAccessBukkitModern
[INFO] checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter | AttackFrequency | FlyingFrequency | KeepAliveFrequency
[INFO] defaults: pvpKnockBackVelocity
[INFO] packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance | NoSlow
[INFO] Hooks: AllViolations~NCP~ 1.0
[INFO] #### Related Plugins ####
[INFO] ProtocolLib v4.5.0-SNAPSHOT
```
### Describe the issue
Trying to take off from ground with an elytra and/or landing on ground, will cause a SF false positive every time.
(Expected behaviour: https://www.dropbox.com/s/glffqxmjnmwuhf0/elytra_take_off2.mov?dl=0)
(With NCP: https://www.dropbox.com/s/hv70thjz1gy8bod/Elytra%20take%20off.mov?dl=0)
### How to reproduce the issue
Just spam the space bar key while wearing an elytra, you should be able to reproduce it quite easily.

### Any possible config options changed or plugins that may cause interference?
Default config, NCP compiled as of [this commit](https://github.com/xaw3ep/NoCheatPlus/commit/d2a2687b8333153a5e7c7758469c5a787cdba9e2).

**Comment by MarkElf** [comment]
Was still able to reproduce post-recent speed changes commit, not that the commit was directed at fixing this in any way. Just saving time if anyone wanted to check if this was still reproducible with the recent commit.
https://github.com/xaw3ep/NoCheatPlus/commit/9828c7e2be1db6414b105a588a32369afa7513ad

**Comment by Lysandr0** [comment]
Small note:
I was also wondering if this could be fixed by using a similar, if not same, technique for the [“fly-nofly” transition fix.](https://github.com/CaptainObvious0/NoCheatPlus/blob/master/NCPCore/src/main/java/fr/neatmonster/nocheatplus/checks/moving/MovingListener.java#L1403) (adding velocity for a short amount of time to prevent SF/CF from triggering)

**Comment by Lysandr0** [comment]
Dropping some debug logs :)
(Setback/Detection)
[Elytra1.log](https://github.com/CaptainObvious0/NoCheatPlus/files/3635911/Elytra1.log)
(With OP status)
[Elytra2.log](https://github.com/CaptainObvious0/NoCheatPlus/files/3635914/Elytra2.log)

**Edit:** I've swiftly tested the [fix attempt](https://github.com/xaw3ep/NoCheatPlus/commit/133f480a7b95114d234a95680b4b5514c9da4af9).     It doesn't seem to have done much, both Survival/Creative Fly still trigger a lot...

**Edit1:** The [new commit](https://github.com/xaw3ep/NoCheatPlus/commit/5527a652884373685bc7022451d2ba7d56e7262c) seems to have fixed everything for the most part :).
I can still get some CreativeFly `(hfrict+vdist/hdist)` and SurvivalFly` (hacc/hbufuse)` violations occasionally, but nowhere near as it originally was.

**Comment by CaptainObvious0** [comment]
Old issue but from my testing elytra works fine with xaw3ep's fork, which will eventually be merged back into master after I add my own changes (awaiting branch). I'll close this issue unless it is still causing issues.
