### ISSUE TITLE
Killaura Bot Bug please fix!

### ISSUE THREAD

**Issue by IWolfZ** [CaptainObvious0/NoCheatPlus#71]
### Full output of /ncp version
3.16.2 
### Describe the issue
NPC bots don't work / they need an update where sometimes a Killaura bot will go around u visible for the player but not visible for other players.

### How to reproduce the issue
Remake the NPC / Citizens killaura bots since they are bypassed and don't work.

### Extra links/Videos (Including debug logs)
- Don't have any
### Any possible config options changed or plugins that may cause interference?
Citizens https://www.spigotmc.org/resources/citizens.13811/

**Comment by CaptainObvious0** [comment]
Not going to implement  https://github.com/NoCheatPlus/Issues/issues/349
