### ISSUE TITLE
PitchPattern attribution?

### ISSUE THREAD

**Issue by Islandscout** [CaptainObvious0/NoCheatPlus#72]
Hi there!

Where's my name for your PitchPattern check?

https://github.com/HawkAnticheat/Hawk/blob/master/src/me/islandscout/hawk/check/movement/look/AimbotPrecision.java

https://github.com/HawkAnticheat/Hawk/blob/master/src/me/islandscout/hawk/util/MathPlus.java#L190

vs

https://github.com/CaptainObvious0/NoCheatPlus/blob/master/NCPCore/src/main/java/fr/neatmonster/nocheatplus/checks/fight/PitchPattern.java

**Comment by CaptainObvious0** [comment]
Added credit in de54f91
